import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import useSWR from 'swr'

const fetcher = (...args) => fetch(...args).then(res => res.json())

function GetInfo() {
  const { data, error } = useSWR('/api/getinfo', fetcher)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  let text = JSON.stringify(data, null, 2)

  return <pre>{text}</pre>
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Just The Tip Jar
        </h1>

        <p className={styles.description}>
          Testing the API with our lightning node!
        </p>

        <GetInfo />

        <div className={styles.grid}>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
